type Query {
    applicationOccurrences: [ApplicationOccurrence!]!
    applicationOccurrence(id: ID!): ApplicationOccurrence
    packageOccurrences: [PackageOccurrence!]!
    packageOccurrence(id: ID!): PackageOccurrence
    vulnerabilities: [Vulnerability!]!
    vulnerability(id: ID!): Vulnerability
}

type ApplicationOccurrence {
    id: ID!
    name: String
    rdfType: String
    bomRef: String
    componentType: String
    group: String
    version: String
    packages: [PackageOccurrence!]!
    vulnerabilities: [Vulnerability!]!
}

type PackageOccurrence {
    id: ID!
    name: String
    rdfType: String
    bomRef: String
    componentType: String
    group: String
    purl: String
    version: String
    applications: [ApplicationOccurrence!]!
    vulnerabilities: [Vulnerability!]!
}

type Vulnerability {
    id: ID!
    rdfType: String
    osv: Osv!
    applications: [ApplicationOccurrence!]!
    packages: [PackageOccurrence!]!
    fixedVersions: [FixedVersion!]!
}

type FixedVersion {
    id: ID!
    packageName: String
    version: String!
    purl: String
}

type Osv {
    osvId: String
    aliases: [String!]!
    summary: String
    details: String
    publishedAt: String
    modifiedAt: String
    withdrawnAt: String
}
